print("I\'m") 
print('""learning""')
print('"""Python"""')
print('Sinal de aspas simples: \'')
print()
print("Sinal de aspas dupla: \"")
print()
print("""Sinal de aspas simples e dupla: " ' """)
print()
print('''Sinal de aspas simples e dupla: " ' ''')
